# Generated by Django 4.2.11 on 2024-05-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_cultural', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='category',
            field=models.CharField(default='Достопримечательности', max_length=30, verbose_name='Тип мероприятия'),
        ),
        migrations.AddField(
            model_name='events_for_visiting',
            name='category',
            field=models.CharField(default='Доступные к посещению', max_length=30, verbose_name='Тип мероприятия'),
        ),
    ]
