# Generated by Django 4.2.11 on 2024-05-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_cultural', '0002_attractions_category_events_for_visiting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractions',
            name='category',
        ),
        migrations.RemoveField(
            model_name='events_for_visiting',
            name='category',
        ),
    ]
