# Generated by Django 4.2.11 on 2024-05-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events_available', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=254, unique=True)),
                ('favourite', models.ManyToManyField(blank=True, default=None, related_name='favourite_product', to='events_available.events_online')),
            ],
        ),
    ]
