# Generated by Django 4.2.11 on 2024-05-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events_cultural', '0004_attractions_category_events_for_visiting_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_cultural.attractions')),
            ],
        ),
    ]
