# Generated by Django 4.2.11 on 2024-05-03 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events_available', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='events_available.events_online')),
            ],
        ),
    ]
