from django.test import TestCase
from django.contrib.auth import get_user_model
from django.utils.crypto import get_random_string

User = get_user_model()

class UserCreationTest(TestCase):
    def test_user_autogenerated_password(self):
        # Данные для создания пользователя без пароля
        email = 'test@example.com'
        first_name = 'Test'
        last_name = 'User'
        middle_name = 'Middle'
        department_id = 1
        telegram_id = get_random_string(8)

        # Создание пользователя без явного задания пароля
        user = User.objects.create_user(email=email, first_name=first_name, last_name=last_name,
                                        middle_name=middle_name, department_id=department_id,
                                        telegram_id=telegram_id)

        # Проверки
        self.assertIsNotNone(user.username, "Username не был сгенерирован")
        self.assertIsNotNone(user.password, "Пароль не был сгенерирован")
        self.assertNotEqual(user.password, '', "Пароль не должен быть пустым")
        self.assertEqual(user.first_name, first_name, "Имя пользователя не соответствует заданному")
        self.assertEqual(user.last_name, last_name, "Фамилия пользователя не соответствует заданной")
        self.assertEqual(user.middle_name, middle_name, "Отчество пользователя не соответствует заданному")
        self.assertEqual(user.department_id, department_id, "ID отдела пользователя не соответствует заданному")
        self.assertEqual(user.telegram_id, telegram_id, "Telegram ID пользователя не соответствует заданному")
