# Generated by Django 4.2.11 on 2024-05-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_available', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_online',
            name='category',
            field=models.CharField(default='Онлайн'),
        ),
    ]
