# Generated by Django 4.2.11 on 2024-05-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_available', '0002_events_online_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_online',
            name='category',
            field=models.CharField(default='Онлайн', max_length=15, verbose_name='Тип мероприятия'),
        ),
    ]
