# Generated by Django 4.2.11 on 2024-05-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_available', '0003_alter_events_online_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_offline',
            name='category',
            field=models.CharField(default='Оффлайн', max_length=30, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='events_online',
            name='category',
            field=models.CharField(default='Онлайн', max_length=30, verbose_name='Тип мероприятия'),
        ),
    ]
